import type { SheriffConfig } from "@softarc/sheriff-core";

export const config: SheriffConfig = {
  autoTagging: false,
  barrelFileName: "__sheriff__.ts",
  enableBarrelLess: true,
  entryPoints: {
    cli: "./packages/cli/src/Cli.ts",
    core: "./packages/core/src/index.ts",
    coreRuntime: "./packages/core/src/Runtime.ts",
    testRuntime: "./packages/core/src/TestRuntime.ts",
  },
  modules: {
    "packages/core/src/domain": "core:domain",
    "packages/core/src/internal": "core:internal",
    "packages/core/src/Session": "core:session",
    "packages/core/src/Task": "core:task",
    "packages/core/src/Sandbox": "core:sandbox",
    "packages/core/src/migrations": "core:migrations",
    "packages/<pkg>/src": "pkg:<pkg>",
  },
  depRules: {
    root: [
      "root",
      "pkg:cli",
      "pkg:core",
      "core:domain",
      "core:internal",
      "core:session",
      "core:task",
      "core:sandbox",
      "core:migrations",
    ],
    "pkg:cli": ["pkg:cli", "pkg:core", "root"],
    "pkg:core": [
      "pkg:core",
      "core:domain",
      "core:internal",
      "core:session",
      "core:task",
      "core:sandbox",
      "core:migrations",
      "root",
    ],
    "core:domain": ["core:domain", "root"],
    "core:internal": ["core:internal", "core:domain", "core:migrations", "root"],
    "core:migrations": ["core:migrations", "root"],
    "core:session": ["core:session", "core:domain", "core:internal", "root"],
    "core:task": ["core:task", "core:domain", "core:internal", "root"],
    "core:sandbox": ["core:sandbox", "core:domain", "core:internal", "root"],
  },
};
